### ISSUE TITLE
MOAR features

### ISSUE THREAD

**Issue by ptahdunbar** [ptahdunbar/yarrs-and-yamls#1]
Add the following to `Vagrantfile.yml`
- [ ] authorize
- [ ] keys
- [x] databases
- [ ] manage system users
- [x] install php + full suite development/production environment
- [x] install latest node + full suite development/production environment
- [ ] switch php versions
- [ ] configure firewalls
- [x] folders
- [x] sites
- [x] memory
- [x] cpus

Example file:

```

---
boxes:
    - hostname: vagrant
      box: ubuntu/trusty64
      memory: 1048
      cpus: 1
      authorize:
        - ~/.ssh/id_dsa.pub
      keys:
        - ~/.ssh/id_dsa
      databases:
        - example_database
      ports:
       - send: 93000
         to: 9300
       - send: 7777
         to: 777
         protocol: udp

```
